name: Android CI/CD

on:
  # Triggers the workflow on every pull request to master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Load API Token from secrets
        env:
          API_TOKEN: ${{ secrets.TOKEN }}
        run: echo API_TOKEN=\"$API_TOKEN\" > ./local.properties

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}


      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Check and Report
        run: ./gradlew lint

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: lint-results-debug
          path: ${{ github.workspace }}/app/build/reports


      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Apk
        run: ./gradlew assembleDebug


      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: ${{ github.workspace }}/app/build/outputs/apk/debug



  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        api-level: [21, 23, 29,30,31]
        target: [default]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Load API Token from secrets
        env:
          API_TOKEN: ${{ secrets.API_OTKEN }}
        run: echo API_TOKEN=\"$API_TOKEN\" > ./local.properties

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11


      - name: Run unit tests
        run: ./gradlew test --stacktrace
      - name: checkout
        uses: actions/checkout@v3

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: Test-Reports
          path: ${{ github.workspace }}/app/build/reports/tests
        if: always()
      

