name: Android CI/CD

on:
  # Triggers the workflow on every pull request to master branch
  push:
    branches: [ master, mahdi ]
  pull_request:
    branches: [ master, mahdi ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}


        - uses: actions/checkout@v1
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

        - name: Change wrapper permissions
          run: chmod +x ./gradlew

        - name: Check and Report
          run: ./gradlew lint

        - name: Upload Report
          uses: actions/upload-artifact@v2
          with:
            name: lint-results-debug
            path: ${{ github.workspace }}/app/build/reports


        - name: Setup Android SDK
          uses: android-actions/setup-android@v2
