name: Run Android Emulator

on:
  push:
    branches:
      - [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2.2.0
        with:
          api-level: 30
          tag: default
          arch: x86
          profile: Nexus 6
      - name: Wait for emulator to finish booting
        run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
      - name: Run UI tests
        run: ./gradlew connectedAndroidTest
